#!/usr/bin/env python3
"""Regenerate src/include/duckdb_nfc_table.h from Python's unicodedata.

Upstream address_standardizer normalizes to NFC before case-mapping so that
decomposed input ("n" + U+0303) matches lexicon entries written in the
precomposed form.  PostgreSQL builds get that from unicode_normalize(); the
DuckDB build gets it from src/include/common/unicode_norm.h, which walks the
table this script emits.

Scope is deliberately U+00C0..U+024F (Latin-1 Supplement, Latin Extended-A/B):
the accented repertoire that turns up in Western address data.  Anything outside
it passes through unchanged.

Usage:  python3 scripts/gen_nfc_table.py > src/include/duckdb_nfc_table.h
"""
import unicodedata
import sys

LOW, HIGH = 0x00C0, 0x0250


def composition_pairs():
    pairs = {}
    for cp in range(LOW, HIGH):
        ch = chr(cp)
        decomp = unicodedata.decomposition(ch)
        if not decomp or decomp.startswith('<'):   # skip compatibility decomps
            continue
        parts = decomp.split()
        if len(parts) != 2:
            continue
        base, mark = int(parts[0], 16), int(parts[1], 16)
        # Keep only pairs that genuinely round-trip, so the table can never
        # compose something NFC itself would leave alone.
        if unicodedata.normalize('NFC', chr(base) + chr(mark)) == ch:
            pairs[(base, mark)] = cp
    return sorted(pairs.items())


def main():
    rows = composition_pairs()
    out = sys.stdout.write
    out("/* Generated by scripts/gen_nfc_table.py -- do not edit by hand.\n")
    out(" * Canonical composition pairs for U+00C0..U+024F (Latin-1 Supplement and\n")
    out(" * Latin Extended-A/B), built from Python's unicodedata. Covers the accented\n")
    out(" * forms that appear in Western address data. */\n")
    out("#ifndef DUCKDB_NFC_TABLE_H\n#define DUCKDB_NFC_TABLE_H\n\n")
    out("typedef struct { unsigned int base, mark, composed; } pagc_nfc_pair;\n\n")
    out("static const pagc_nfc_pair pagc_nfc_pairs[] = {\n")
    for (base, mark), composed in rows:
        out("    {0x%04X, 0x%04X, 0x%04X},\n" % (base, mark, composed))
    out("};\n\n")
    out("#define PAGC_NFC_PAIR_COUNT %d\n\n" % len(rows))
    out("#endif /* DUCKDB_NFC_TABLE_H */\n")


if __name__ == '__main__':
    main()
